In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df.shape

(768, 9)

In [5]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [8]:
x = df.iloc[:,:-1]   # df.drop('Outcome',axis=1)
y = df.iloc[:,-1]   # df['Outcome']
print(x.shape)
print(y.shape)
print(type(x))
print(type(y))

(768, 8)
(768,)
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [9]:
x.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [10]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(576, 8)
(192, 8)
(576,)
(192,)


In [14]:
768*0.75

576.0

In [26]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [18]:
def gen_metrics(ytest,ypred):
    cm = confusion_matrix(ytest,ypred)
    print('confusion matrix\n',cm)
    print('Classification report\n',classification_report(ytest,ypred))
    print('Acc score',accuracy_score(ytest,ypred))

#### Build Models

#### 1) Log Reg

In [19]:
from sklearn.linear_model import LogisticRegression

In [22]:
m1 = LogisticRegression(max_iter=1000)
m1.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [23]:
print('Training score',m1.score(x_train,y_train))
print('Testing score',m1.score(x_test,y_test))

Training score 0.7586805555555556
Testing score 0.84375


In [24]:
ypred_m1 = m1.predict(x_test)
print(ypred_m1)

[1 0 0 1 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0
 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1
 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0
 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 1
 0 0 1 0 0 0 1]


In [27]:
gen_metrics(y_test,ypred_m1)

confusion matrix
 [[117   7]
 [ 23  45]]
Classification report
               precision    recall  f1-score   support

           0       0.84      0.94      0.89       124
           1       0.87      0.66      0.75        68

    accuracy                           0.84       192
   macro avg       0.85      0.80      0.82       192
weighted avg       0.85      0.84      0.84       192

Acc score 0.84375


#### 2) KNN

In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [34]:
m2 = KNeighborsClassifier(n_neighbors=17)
m2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=17)

In [35]:
print('Training score',m2.score(x_train,y_train))
print('Testing score',m2.score(x_test,y_test))

Training score 0.7673611111111112
Testing score 0.78125


In [36]:
ypred_m2 = m2.predict(x_test)
print(ypred_m2)

[0 0 0 1 1 0 0 1 1 0 1 1 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 1 1 0
 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0
 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0
 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 0 1 0 1 0 0 0 0 1 1 0 0 1 1 1 0 1 1
 0 0 0 0 0 0 1]


In [37]:
gen_metrics(y_test,ypred_m2)

confusion matrix
 [[108  16]
 [ 26  42]]
Classification report
               precision    recall  f1-score   support

           0       0.81      0.87      0.84       124
           1       0.72      0.62      0.67        68

    accuracy                           0.78       192
   macro avg       0.77      0.74      0.75       192
weighted avg       0.78      0.78      0.78       192

Acc score 0.78125


### 3) DT

In [39]:
from sklearn.tree import DecisionTreeClassifier

In [56]:
m3 = DecisionTreeClassifier(criterion='gini',max_depth=5,min_samples_split=15)
# 
m3.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=5, min_samples_split=15)

In [57]:
print('Training score',m3.score(x_train,y_train))
print('Testing score',m3.score(x_test,y_test))

Training score 0.8298611111111112
Testing score 0.7604166666666666


In [58]:
ypred_m3 = m3.predict(x_test)
print(ypred_m3)

[1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 0 1 1 0
 0 0 1 0 0 1 1 1 0 0 0 0 1 0 1 1 0 0 1 1 0 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0
 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 1 0 1 1 0 0 0 0 1 0 0 1 0 1 0 0 1
 0 0 1 0 0 0 0]


In [59]:
gen_metrics(y_test,ypred_m3)

confusion matrix
 [[108  16]
 [ 30  38]]
Classification report
               precision    recall  f1-score   support

           0       0.78      0.87      0.82       124
           1       0.70      0.56      0.62        68

    accuracy                           0.76       192
   macro avg       0.74      0.71      0.72       192
weighted avg       0.75      0.76      0.75       192

Acc score 0.7604166666666666


#### 4) Random Forest

In [60]:
from sklearn.ensemble import RandomForestClassifier

In [62]:
m4 = RandomForestClassifier(n_estimators=50,criterion='entropy',max_depth=6,min_samples_split=12)
m4.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=6, min_samples_split=12,
                       n_estimators=50)

In [63]:
print('Training score',m4.score(x_train,y_train))
print('Testing score',m4.score(x_test,y_test))

Training score 0.8611111111111112
Testing score 0.8177083333333334


In [64]:
ypred_m4 = m4.predict(x_test)
print(ypred_m4)

[1 0 0 1 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0
 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0
 1 0 1 0 0 0 0 0 1 0 0 1 0 1 1 0 0 1 0 0 1 0 1 0 0 0 0 1 1 0 0 1 1 1 0 1 1
 0 0 1 0 0 0 1]


In [65]:
gen_metrics(y_test,ypred_m4)

confusion matrix
 [[113  11]
 [ 24  44]]
Classification report
               precision    recall  f1-score   support

           0       0.82      0.91      0.87       124
           1       0.80      0.65      0.72        68

    accuracy                           0.82       192
   macro avg       0.81      0.78      0.79       192
weighted avg       0.82      0.82      0.81       192

Acc score 0.8177083333333334


#### 5) SVM

In [66]:
from sklearn.svm import SVC

In [67]:
m5 = SVC(kernel='linear',C=1)
m5.fit(x_train,y_train)

SVC(C=1, kernel='linear')

In [68]:
print('Training score',m5.score(x_train,y_train))
print('Testing score',m5.score(x_test,y_test))

Training score 0.7621527777777778
Testing score 0.828125


In [69]:
ypred_m5 = m5.predict(x_test)
print(ypred_m5)

[1 0 0 1 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0
 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1
 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0
 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 1
 0 0 1 0 0 0 1]


In [70]:
gen_metrics(y_test,ypred_m5)

confusion matrix
 [[114  10]
 [ 23  45]]
Classification report
               precision    recall  f1-score   support

           0       0.83      0.92      0.87       124
           1       0.82      0.66      0.73        68

    accuracy                           0.83       192
   macro avg       0.83      0.79      0.80       192
weighted avg       0.83      0.83      0.82       192

Acc score 0.828125


#### Conclusion
1) Log_Reg is the best performining model in terms of accuracy.<br>
2) Log_Reg and SVC are the best performining model in terms of recall<br>