In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('winequality-red.csv')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
df.shape

(1599, 12)

In [5]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [6]:
df['quality'].value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [7]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [8]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
print(x.shape)
print(y.shape)
print(type(x))
print(type(y))

(1599, 11)
(1599,)
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [9]:
x.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [10]:
y.head()

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1119, 11)
(480, 11)
(1119,)
(480,)


In [83]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [53]:
def gen_metrics(ytest,ypred):
    cm = confusion_matrix(ytest,ypred)
    print('Confusion Matrix\n',cm)
    print('Classfication Report\n',classification_report(ytest,ypred,zero_division=0))
    
def tt_score(model):
    print('Training Score',model.score(x_train,y_train))
    print('Testing Score',model.score(x_test,y_test))

### 1) LogisticReg

In [17]:
from sklearn.linear_model import LogisticRegression

In [23]:
m1 = LogisticRegression(max_iter=1000,solver='liblinear')
m1.fit(x_train,y_train)

LogisticRegression(max_iter=1000, solver='liblinear')

In [25]:
tt_score(m1)

Training Score 0.6041108132260947
Testing Score 0.5583333333333333


In [26]:
ypred_m1 = m1.predict(x_test)
print(ypred_m1)

[6 5 6 5 5 5 6 5 5 6 6 5 6 7 6 6 6 6 5 5 5 6 6 5 6 6 5 5 5 5 5 6 6 5 6 5 5
 6 6 6 6 6 6 6 6 5 5 5 5 6 5 6 6 5 5 5 6 5 5 5 5 6 6 5 6 5 5 5 6 6 5 5 6 5
 5 6 5 5 5 5 5 6 5 6 6 6 5 5 6 6 5 5 6 6 6 6 6 5 6 6 7 6 5 6 6 6 6 6 5 5 5
 5 5 6 6 6 5 5 5 6 5 6 6 5 5 5 6 6 5 7 5 6 5 6 6 5 6 6 6 5 6 5 5 6 6 5 6 5
 5 6 5 5 5 6 5 7 6 5 5 5 6 7 5 6 5 5 5 5 5 6 5 5 5 5 5 5 5 6 6 7 5 7 6 6 5
 6 5 5 5 6 6 5 5 6 5 6 5 6 5 5 5 5 5 6 6 6 5 5 5 5 6 6 6 6 6 6 5 5 5 6 6 6
 5 5 5 5 5 5 6 6 5 5 5 5 6 5 5 6 6 5 7 5 5 6 6 6 6 5 5 6 5 5 5 5 6 5 6 6 6
 6 5 6 5 6 6 5 6 5 5 6 6 5 6 5 5 5 5 5 6 6 5 5 5 6 6 5 5 5 6 6 6 5 5 6 6 6
 5 5 6 5 6 6 5 5 6 5 5 6 5 7 5 6 7 5 5 6 6 6 6 5 6 5 5 5 5 6 6 5 5 5 5 6 6
 5 5 6 6 6 6 6 5 5 6 5 6 5 6 5 5 5 6 6 6 6 5 6 5 5 5 6 6 6 5 5 5 5 6 5 6 5
 6 5 6 5 6 6 7 6 5 5 5 5 5 5 5 5 6 5 6 5 6 5 6 5 6 5 5 6 6 5 5 6 5 6 5 6 6
 5 5 6 5 6 5 5 5 5 6 5 5 5 5 5 5 7 6 5 6 6 5 5 5 5 7 5 5 6 5 5 5 5 5 5 6 6
 6 6 5 5 7 5 5 5 6 5 6 5 6 5 5 6 5 6 6 5 5 6 5 5 5 6 5 5 6 5 5 5 5 5 5 6]


In [27]:
gen_metrics(y_test,ypred_m1)

Confusion Matrix
 [[  0   0   2   0   0   0]
 [  0   0  13   2   0   0]
 [  0   0 151  39   0   0]
 [  0   0  85 112   7   0]
 [  0   0  11  46   5   0]
 [  0   0   1   4   2   0]]
Classfication Report
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        15
           5       0.57      0.79      0.67       190
           6       0.55      0.55      0.55       204
           7       0.36      0.08      0.13        62
           8       0.00      0.00      0.00         7

    accuracy                           0.56       480
   macro avg       0.25      0.24      0.22       480
weighted avg       0.51      0.56      0.51       480



C:\Users\Dell\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Dell\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Dell\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### 2) Decision Tree

In [28]:
from sklearn.tree import DecisionTreeClassifier

In [34]:
m2 = DecisionTreeClassifier(criterion='entropy',max_depth=15)
m2.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=15)

In [35]:
tt_score(m2)

Training Score 0.9919571045576407
Testing Score 0.6


In [36]:
ypred_m2 = m2.predict(x_test)
print(ypred_m2)

[5 5 7 5 6 4 6 6 4 5 6 5 6 6 6 7 7 7 5 5 6 6 5 6 5 6 5 5 6 5 5 6 6 6 7 7 5
 7 5 6 7 6 5 6 7 5 5 6 5 5 6 5 6 5 6 6 6 5 5 5 5 7 6 5 5 6 6 6 6 5 5 5 5 3
 5 6 5 6 5 5 5 6 6 6 7 7 5 6 7 6 5 6 7 5 6 7 7 5 6 6 5 6 6 7 6 6 6 6 5 5 6
 6 6 6 6 6 5 6 5 6 5 5 6 5 5 5 6 6 5 7 6 7 6 5 7 5 6 6 6 5 6 4 5 6 7 5 6 7
 6 6 5 5 5 5 6 7 7 6 5 5 5 5 5 6 7 5 5 6 5 5 6 5 4 6 6 4 6 5 7 5 5 7 6 6 6
 5 5 6 4 6 5 6 5 6 5 6 5 6 5 5 5 5 3 7 7 7 6 5 5 5 5 6 7 7 6 5 5 6 5 6 7 6
 3 6 5 6 5 6 6 6 6 5 7 6 6 6 5 5 6 4 7 5 5 6 6 7 6 6 5 6 5 5 6 4 7 7 6 5 5
 6 5 5 5 6 6 5 5 6 5 5 6 4 6 5 5 5 5 5 5 5 5 5 5 6 6 5 6 5 5 4 5 5 5 7 6 7
 6 5 6 5 7 7 5 5 7 5 5 7 5 7 5 5 8 6 5 6 6 6 7 5 6 6 6 3 6 7 7 5 5 5 5 6 5
 6 4 6 6 7 7 6 5 5 5 5 6 5 6 5 6 5 5 6 6 6 5 6 5 5 5 5 6 6 6 6 5 6 7 5 6 6
 6 5 6 5 7 6 5 6 5 5 5 4 5 6 5 5 5 6 7 6 5 4 6 5 7 5 5 7 6 5 6 7 6 5 5 6 6
 5 6 5 4 6 6 5 6 5 6 5 5 5 5 5 5 6 6 6 6 5 5 5 4 5 6 5 6 6 5 5 6 5 5 5 5 6
 5 6 5 5 7 6 6 5 6 5 6 5 5 5 5 6 5 6 5 5 6 5 5 5 6 5 6 5 6 5 6 5 6 6 6 5]


In [37]:
gen_metrics(y_test,ypred_m2)

Confusion Matrix
 [[  0   0   1   1   0   0]
 [  2   1   8   4   0   0]
 [  1   7 142  37   3   0]
 [  1   6  57 117  22   1]
 [  0   1   6  27  28   0]
 [  0   0   1   2   4   0]]
Classfication Report
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.07      0.07      0.07        15
           5       0.66      0.75      0.70       190
           6       0.62      0.57      0.60       204
           7       0.49      0.45      0.47        62
           8       0.00      0.00      0.00         7

    accuracy                           0.60       480
   macro avg       0.31      0.31      0.31       480
weighted avg       0.59      0.60      0.59       480



### 3) KNN

In [38]:
from sklearn.neighbors import KNeighborsClassifier

In [49]:
m3 = KNeighborsClassifier(n_neighbors=17)
m3.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=17)

In [50]:
tt_score(m3)

Training Score 0.5862377122430742
Testing Score 0.48541666666666666


In [51]:
ypred_m3 = m3.predict(x_test)
print(ypred_m3)

[7 5 6 5 5 5 6 6 6 5 6 5 7 5 6 6 6 5 6 5 5 5 5 6 5 6 5 5 5 6 5 6 6 6 6 6 5
 5 6 6 5 5 6 6 5 5 5 6 6 5 5 6 6 5 5 6 5 6 6 5 5 7 6 5 5 5 7 5 6 6 5 5 5 5
 5 6 5 5 5 5 5 6 5 5 5 6 5 5 6 6 5 6 6 6 5 5 6 5 6 5 6 6 5 6 5 5 6 5 6 5 6
 5 5 6 5 5 5 5 5 5 5 6 7 6 5 6 5 6 5 6 5 6 6 6 6 6 5 5 6 5 6 5 5 6 6 5 5 5
 6 6 5 5 5 5 5 7 6 5 5 6 5 6 5 5 5 5 5 5 5 6 5 5 5 6 5 5 5 5 6 5 5 6 7 7 5
 5 5 5 6 5 5 5 5 6 5 6 5 6 5 5 5 5 5 6 6 6 5 5 6 5 5 5 5 5 6 6 5 5 6 5 6 5
 6 6 5 5 5 6 5 5 5 5 5 5 5 5 6 5 5 5 7 5 5 5 5 6 7 5 5 5 6 5 6 6 5 5 6 6 6
 5 5 5 5 6 7 5 6 5 5 6 6 6 6 5 5 6 5 5 6 6 5 5 5 6 6 5 5 5 6 7 6 5 6 7 6 5
 5 5 6 6 6 6 6 5 5 5 5 6 5 6 6 5 6 5 5 6 6 5 7 6 6 6 6 5 6 5 6 6 5 5 5 5 5
 5 5 6 5 7 6 6 6 5 6 5 6 5 6 5 5 5 5 6 5 6 5 6 5 5 5 5 5 5 5 5 5 6 5 5 5 5
 6 5 5 5 6 7 6 6 5 5 5 5 5 5 6 5 7 5 5 5 5 5 5 5 6 5 6 5 5 5 6 7 5 5 5 5 5
 5 6 5 5 5 6 5 5 5 6 5 5 5 5 5 6 6 5 5 6 5 5 5 5 6 7 5 5 6 5 5 5 6 6 5 6 5
 6 5 5 6 6 5 5 6 5 5 6 5 6 6 5 5 6 6 5 5 6 5 7 5 5 7 6 5 6 5 5 5 5 5 5 6]


In [54]:
gen_metrics(y_test,ypred_m3)

Confusion Matrix
 [[  0   0   1   1   0   0]
 [  0   0  11   4   0   0]
 [  0   0 138  49   3   0]
 [  0   0 112  85   7   0]
 [  0   0  25  27  10   0]
 [  0   0   2   4   1   0]]
Classfication Report
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        15
           5       0.48      0.73      0.58       190
           6       0.50      0.42      0.45       204
           7       0.48      0.16      0.24        62
           8       0.00      0.00      0.00         7

    accuracy                           0.49       480
   macro avg       0.24      0.22      0.21       480
weighted avg       0.46      0.49      0.45       480



### 4) SVM

In [55]:
from sklearn.svm import SVC

In [65]:
m4 = SVC(kernel='poly',C=100,degree=4)
m4.fit(x_train,y_train)

SVC(C=100, degree=4, kernel='poly')

In [66]:
tt_score(m4)

Training Score 0.579088471849866
Testing Score 0.55


In [67]:
ypred_m4 = m4.predict(x_test)
print(ypred_m4)

[6 5 6 5 5 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 6 5 5 5 6 5 5 6 6 6 6 5
 7 6 6 6 6 6 6 5 6 5 5 6 6 6 6 6 5 6 6 6 6 6 5 5 6 6 5 6 5 6 5 6 6 5 5 5 5
 5 6 6 5 5 5 6 6 5 6 6 6 5 5 6 6 5 6 6 6 6 7 6 5 6 5 6 6 6 6 5 6 6 6 6 6 6
 5 5 6 6 6 5 5 6 6 5 6 6 5 5 5 6 6 5 6 5 6 6 6 6 6 6 6 6 5 6 6 5 6 6 5 6 5
 5 6 6 5 6 7 5 6 6 6 5 6 6 6 5 6 5 5 5 5 6 6 5 5 5 6 6 6 6 6 6 6 5 6 6 6 5
 6 5 5 6 6 5 5 5 6 5 6 5 6 5 5 5 5 6 6 6 6 5 6 6 5 5 6 6 6 6 6 5 6 6 6 6 6
 6 6 5 5 5 5 6 6 5 6 7 6 6 5 6 6 6 5 6 5 5 6 6 6 6 5 5 6 5 5 6 6 6 5 6 5 6
 6 5 5 5 6 6 5 6 5 6 6 6 6 6 6 5 5 5 5 6 6 5 5 6 6 6 5 5 5 6 6 6 5 6 6 6 6
 6 5 6 6 6 5 6 5 6 5 5 6 6 6 6 6 6 6 5 6 6 6 6 6 6 5 6 5 5 6 6 6 5 5 6 6 6
 5 6 6 6 6 6 6 6 5 6 5 6 5 6 5 5 5 6 6 6 6 5 6 5 5 5 6 6 5 5 6 5 6 6 5 6 6
 6 5 6 6 6 6 6 6 6 5 5 5 6 6 6 6 6 5 6 5 6 6 6 5 6 5 6 6 6 5 6 6 6 6 5 6 6
 5 6 7 5 6 6 5 5 5 6 5 6 5 5 6 6 6 6 6 6 6 6 5 6 6 6 5 6 6 5 5 5 6 5 6 6 6
 6 6 5 6 6 5 5 6 6 5 6 5 6 6 5 6 6 6 5 5 6 6 5 5 5 6 5 6 6 5 5 6 6 6 6 6]


In [68]:
gen_metrics(y_test,ypred_m4)

Confusion Matrix
 [[  0   0   1   1   0   0]
 [  0   0  11   4   0   0]
 [  0   0 106  84   0   0]
 [  0   0  46 155   3   0]
 [  0   0   6  53   3   0]
 [  0   0   1   6   0   0]]
Classfication Report
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        15
           5       0.62      0.56      0.59       190
           6       0.51      0.76      0.61       204
           7       0.50      0.05      0.09        62
           8       0.00      0.00      0.00         7

    accuracy                           0.55       480
   macro avg       0.27      0.23      0.21       480
weighted avg       0.53      0.55      0.50       480



### 5) RandomForestClassifier

In [71]:
from sklearn.ensemble import RandomForestClassifier

In [72]:
m5 = RandomForestClassifier(n_estimators=80,criterion='gini',max_depth=9)
m5.fit(x_train,y_train)

RandomForestClassifier(max_depth=9, n_estimators=80)

In [73]:
tt_score(m5)

Training Score 0.9186773905272565
Testing Score 0.6520833333333333


In [74]:
ypred_m5 = m5.predict(x_test)
print(ypred_m5)

[6 5 7 5 6 5 6 5 5 6 7 5 7 6 6 6 6 6 5 5 6 6 6 6 7 6 5 5 6 6 5 6 6 5 6 6 5
 7 6 6 6 6 6 6 7 6 5 6 5 5 6 6 6 5 6 6 6 5 6 5 5 7 6 5 6 5 6 5 5 5 5 5 5 5
 5 6 6 6 6 5 5 6 6 6 6 7 5 5 6 6 5 6 7 5 6 6 6 5 6 6 6 6 5 7 6 6 6 7 6 5 6
 5 5 6 6 7 5 5 5 6 5 6 6 5 5 6 6 6 5 7 6 6 6 7 6 5 6 6 6 5 5 5 5 6 7 5 6 7
 6 6 5 5 5 7 5 7 7 5 5 6 5 6 5 6 5 5 5 5 5 5 5 5 5 5 5 6 6 5 7 7 5 6 6 6 5
 5 5 5 5 6 5 6 5 6 5 6 5 6 5 5 5 5 6 6 6 6 6 5 6 5 5 7 6 6 6 5 5 6 5 6 7 6
 6 5 5 5 5 5 6 6 5 5 7 5 7 6 5 5 5 5 7 5 5 6 6 6 6 5 5 6 5 5 6 5 6 5 6 5 5
 7 5 5 5 6 6 5 6 5 5 6 6 6 6 5 5 5 5 5 6 6 5 5 6 6 6 6 5 5 5 6 6 5 5 7 6 6
 6 5 6 5 7 7 5 5 6 5 5 6 5 6 5 5 7 5 5 6 6 6 7 5 6 5 6 5 6 7 7 5 5 5 5 6 6
 5 5 6 6 6 6 7 5 5 5 5 6 6 6 5 5 5 5 6 6 6 5 6 5 5 5 6 6 6 5 5 5 6 6 5 6 5
 6 5 6 5 6 7 6 6 6 5 5 5 5 5 6 5 5 5 6 6 5 6 6 5 6 5 5 6 7 5 5 7 5 6 5 6 6
 5 6 7 5 6 5 5 6 5 6 5 5 5 5 5 5 7 6 6 6 5 5 5 6 5 7 5 5 7 5 5 5 5 6 6 5 6
 6 7 5 5 7 5 5 5 6 5 6 5 5 5 5 6 5 6 5 5 6 6 5 5 5 6 5 5 6 5 5 5 6 6 5 5]


In [77]:
from collections import Counter
c1 = Counter(ypred_m5)
print(c1)

Counter({5: 234, 6: 202, 7: 44})


In [75]:
gen_metrics(y_test,ypred_m5)

Confusion Matrix
 [[  0   0   1   1   0   0]
 [  0   0  10   5   0   0]
 [  0   0 153  36   1   0]
 [  0   0  63 131  10   0]
 [  0   0   7  26  29   0]
 [  0   0   0   3   4   0]]
Classfication Report
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        15
           5       0.65      0.81      0.72       190
           6       0.65      0.64      0.65       204
           7       0.66      0.47      0.55        62
           8       0.00      0.00      0.00         7

    accuracy                           0.65       480
   macro avg       0.33      0.32      0.32       480
weighted avg       0.62      0.65      0.63       480



Fucntion to handle any model

In [78]:
def model_perf(model,x_train,x_test,y_train,y_test):
    
# train_score
# test_score
# ypred
# cm
# cls_report

In [85]:
def model_perf(model, x_train,x_test,y_test, y_train):
    model.fit(x_train,y_train)
    ypred = model.predict(x_test)
    print(ypred)
    cm = confusion_matrix(y_test,ypred)
    print('confusion matrix\n',cm)
    print('Classification report\n',classification_report(y_test,ypred,zero_division=0))
    print('Acc score',accuracy_score(y_test,ypred))
    
    print('Training score',model.score(x_train,y_train))
    print('Testing score',model.score(x_test,y_test))


In [86]:
w1 = LogisticRegression(max_iter=1000,solver='liblinear')
model_perf(w1, x_train,x_test,y_test, y_train)

[6 5 6 5 5 5 6 5 5 6 6 5 6 7 6 6 6 6 5 5 5 6 6 5 6 6 5 5 5 5 5 6 6 5 6 5 5
 6 6 6 6 6 6 6 6 5 5 5 5 6 5 6 6 5 5 5 6 5 5 5 5 6 6 5 6 5 5 5 6 6 5 5 6 5
 5 6 5 5 5 5 5 6 5 6 6 6 5 5 6 6 5 5 6 6 6 6 6 5 6 6 7 6 5 6 6 6 6 6 5 5 5
 5 5 6 6 6 5 5 5 6 5 6 6 5 5 5 6 6 5 7 5 6 5 6 6 5 6 6 6 5 6 5 5 6 6 5 6 5
 5 6 5 5 5 6 5 7 6 5 5 5 6 7 5 6 5 5 5 5 5 6 5 5 5 5 5 5 5 6 6 7 5 7 6 6 5
 6 5 5 5 6 6 5 5 6 5 6 5 6 5 5 5 5 5 6 6 6 5 5 5 5 6 6 6 6 6 6 5 5 5 6 6 6
 5 5 5 5 5 5 6 6 5 5 5 5 6 5 5 6 6 5 7 5 5 6 6 6 6 5 5 6 5 5 5 5 6 5 6 6 6
 6 5 6 5 6 6 5 6 5 5 6 6 5 6 5 5 5 5 5 6 6 5 5 5 6 6 5 5 5 6 6 6 5 5 6 6 6
 5 5 6 5 6 6 5 5 6 5 5 6 5 7 5 6 7 5 5 6 6 6 6 5 6 5 5 5 5 6 6 5 5 5 5 6 6
 5 5 6 6 6 6 6 5 5 6 5 6 5 6 5 5 5 6 6 6 6 5 6 5 5 5 6 6 6 5 5 5 5 6 5 6 5
 6 5 6 5 6 6 7 6 5 5 5 5 5 5 5 5 6 5 6 5 6 5 6 5 6 5 5 6 6 5 5 6 5 6 5 6 6
 5 5 6 5 6 5 5 5 5 6 5 5 5 5 5 5 7 6 5 6 6 5 5 5 5 7 5 5 6 5 5 5 5 5 5 6 6
 6 6 5 5 7 5 5 5 6 5 6 5 6 5 5 6 5 6 6 5 5 6 5 5 5 6 5 5 6 5 5 5 5 5 5 6]
confusion matrix
 [[  0   

In [87]:
w2 = DecisionTreeClassifier(criterion='gini',max_depth=9,min_samples_split=17)
model_perf(w2, x_train,x_test,y_test, y_train)

[6 5 5 5 6 6 7 5 6 7 7 7 7 6 6 5 6 5 5 5 5 6 5 5 5 6 5 5 5 5 5 6 6 5 5 7 5
 6 6 5 6 5 6 6 5 6 5 5 5 5 5 5 6 5 6 6 6 6 5 5 6 6 6 5 5 4 6 5 6 5 5 5 5 6
 5 6 6 5 5 6 6 6 4 5 7 7 5 5 6 6 5 6 7 7 6 6 6 5 6 6 6 6 5 7 6 6 7 7 5 5 5
 5 5 6 5 7 5 5 5 5 6 6 6 5 5 6 5 6 5 7 6 7 7 6 7 5 6 5 6 5 5 5 5 5 6 5 6 6
 6 6 5 6 5 6 5 7 7 6 5 5 5 7 5 5 5 5 6 5 5 6 6 6 5 5 5 5 6 5 7 7 4 7 6 6 6
 5 5 5 5 6 5 6 5 6 5 6 5 6 5 5 5 5 6 7 6 6 6 5 5 5 6 7 7 7 6 5 5 6 5 4 5 6
 4 6 5 5 5 5 5 6 4 5 6 5 6 5 5 5 5 5 7 5 5 5 5 7 6 5 5 6 5 6 5 5 5 4 5 6 5
 6 5 5 5 6 7 5 6 6 5 5 6 6 7 6 5 5 5 5 5 7 5 5 5 6 6 5 6 5 7 4 5 5 5 7 6 7
 4 6 6 5 6 5 5 5 5 5 5 6 5 6 5 5 6 5 5 6 6 6 6 6 5 5 6 5 6 7 7 5 5 5 5 6 5
 5 5 6 6 7 7 6 5 5 5 5 5 5 6 5 5 6 6 6 6 6 6 6 6 5 5 6 5 6 5 6 5 5 6 5 6 6
 6 5 5 5 6 6 6 6 6 5 5 5 5 5 5 6 5 6 6 6 6 4 6 5 6 5 5 7 6 5 5 7 4 6 5 5 6
 5 6 6 5 6 5 5 6 5 5 5 5 5 5 5 5 6 6 6 6 6 5 5 5 5 7 5 5 6 5 5 5 5 6 6 5 6
 6 6 5 5 7 5 5 5 5 5 6 5 5 5 6 7 5 6 5 5 5 6 5 5 6 5 5 5 4 5 6 6 6 6 5 5]
confusion matrix
 [[  0   