### Numpy

In [2]:
import numpy as np

#### Numpy Arrays

1) Numpy array are like list but in numy arrays all the elements have the same data type.<br>
2) Numpy arrays are represented in []<br>
3) Each numpy array will bear these attributes<br>
    
    a) ndim - no of dimensions
    b) size - no of elements in the array
    c) dtype - data type of the numpy array
    d) shape - represents no of rows and columns (in 2D and higher dimension arrays)

### Numpy Array Creation Methods

#### 1) np.zeros()

In [6]:
n1 = np.zeros((2,2))
print(n1)
print(n1.ndim)
print(n1.size)
print(n1.shape)
print(n1.dtype)

[[0. 0.]
 [0. 0.]]
2
4
(2, 2)
float64


In [7]:
n2 = np.zeros((7))
print(n2)

[0. 0. 0. 0. 0. 0. 0.]


In [8]:
n3 = np.zeros((3,4),dtype=int)
print(n3)
print(n3.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(3, 4)


#### 2) np.ones()

In [11]:
n4 = np.ones((4,3),dtype=int)
print(n4)
print(n4.ndim)
print(n4.size)
print(n4.shape)
print(n4.dtype)
print(type(n4))

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
2
12
(4, 3)
int32
<class 'numpy.ndarray'>


In [15]:
n5 = np.ones((3,4,2))  # 3 = 3rd dim, 4 =rows, 2=cols
print(n5)
print(n5.shape)
print(n5.ndim)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
(3, 4, 2)
3


#### 3) np.identity()

In [21]:
r = np.identity(4)
print(r)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
r1 = np.identity(3)
print(r1)
print(r1.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


#### 4) np.linspace()
Generates linearly spaced elements in the given range

In [27]:
t1 = np.linspace(2,10,5)  # start=2,stop=10, num=5
print(t1)
t2 = np.linspace(2,10,3)  # start = 2,end=10,num=3
print(t2)

[ 2.  4.  6.  8. 10.]
[ 2.  6. 10.]


In [28]:
t3 = np.linspace(3,15,8)
print(t3)

[ 3.          4.71428571  6.42857143  8.14285714  9.85714286 11.57142857
 13.28571429 15.        ]


In [31]:
t4 = np.linspace(5,20)
print(t4)
print(len(t4))

[ 5.          5.30612245  5.6122449   5.91836735  6.2244898   6.53061224
  6.83673469  7.14285714  7.44897959  7.75510204  8.06122449  8.36734694
  8.67346939  8.97959184  9.28571429  9.59183673  9.89795918 10.20408163
 10.51020408 10.81632653 11.12244898 11.42857143 11.73469388 12.04081633
 12.34693878 12.65306122 12.95918367 13.26530612 13.57142857 13.87755102
 14.18367347 14.48979592 14.79591837 15.10204082 15.40816327 15.71428571
 16.02040816 16.32653061 16.63265306 16.93877551 17.24489796 17.55102041
 17.85714286 18.16326531 18.46938776 18.7755102  19.08163265 19.3877551
 19.69387755 20.        ]
50


In [33]:
t4 = np.linspace(7,15,5,retstep=True)
print(t4)
print(len(t4))

(array([ 7.,  9., 11., 13., 15.]), 2.0)
2


#### 5) np.array()

In [36]:
n1 = np.array([10,20,23,34,45,46])
print(n1)
print(n1.ndim)
print(n1.size)
print(n1.shape)
print(n1.dtype)

[10 20 23 34 45 46]
1
6
(6,)
int32


#### Creating numpy array using list, tuple

In [38]:
n2 = np.array(((4,5,6),(7,8,9),(10,11,12)))
print(n2)
print(n2.ndim)
print(n2.size)
print(n2.shape)
print(n2.dtype)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
9
(3, 3)
int32


#### Reshape the array
A numpy array can be reshaped in terms of product of its factors

In [42]:
# Factors of 12 = 1,2,3,4,6,12
d1 = np.array([10,20,30,40,50,60,5,15,25,35,45,55]).reshape(1,12)
print(d1)
print(d1.shape)
print(len(d1))

[[10 20 30 40 50 60  5 15 25 35 45 55]]
(1, 12)
1


In [46]:
# Factors of 18 - 1,2,3,6,9,18
d2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]).reshape(2,3,3)
print(d2)
print(d2.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
(2, 3, 3)


#### 6) np.arange()

In [48]:
a1 = np.arange(10,15) # start=10,end=15,step=1
print(a1)

[10 11 12 13 14]


In [52]:
a2 = np.arange(12,50,7) # start=12,end=50 step=7
print(a2)

[12 19 26 33 40 47]


In [55]:
a3 = np.arange(10,5,-1)  # start=10,end=5,step=-1
print(a3)

[10  9  8  7  6]


#### np.where()
Returns index of the matching conditions

In [57]:
r = np.array([10,12,14,15,17,18,21,23,34,10])
# Syntax - 1 - returns index
r1_index = np.where(r%2==0)
print(r1_index)

# Fetch values corresponding to the indexes
print(r[r1_index])

(array([0, 1, 2, 5, 8, 9], dtype=int64),)
[10 12 14 18 34 10]


In [58]:
# Syntax - 2 => returns values - Acts as if-else
print(r)
r2 = np.where(r%2==0,r+3,r-7) 
# If elements of array r are divisible by 2, then add 3 to them, otherwise subtract 7 from them
print(r2)


[10 12 14 15 17 18 21 23 34 10]
[13 15 17  8 10 21 14 16 37 13]
